[build]
  base = "/"
  publish = "dist"
  command = "npm run build"

# Proxy para as chamadas de API em produção
# Substitua 'seu-backend-real.onrender.com' pela URL real do seu backend no Render
[[redirects]]
  from = "/api/*"
  to = "https://seu-backend-real.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"}

# Para requisições OPTIONS (preflight CORS)
[[redirects]]
  from = "/api/*"
  to = "https://seu-backend-real.onrender.com/api/:splat"
  status = 204
  force = true
  methods = ["OPTIONS"]
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"}

# Redirecionamento para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200